### ISSUE TITLE
babel-plugin-transform-builtin-classes breaks some of my classes.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1517] opened 2018-08-25 17:30 UTC
## Bug report

* Skate version: 62c62126b991c83db818633b9237081c8fd04cdf
* Affected browsers (and versions): N/A

### Current behaviour

My pull request #1510 (and probably related pull requests) seem to have broken after rebasing on master.

What happens now is that in some classes, I have to catch constructor return values otherwise context gets lost, and I'm using a custom class system. This is what I mean:

```js
Class('Foo').extends(withUpdate(class{}), ({ Super }) => {
  constructor() {
    const _this = Super(this).constructor()
    // use _this, not this
  },
}))
```

As you may recall, I'm using `withUpdate` on non-HTMLElement classes, which is working great!

But it seems the recent changes now require me to catch the constructor return value, otherwise `this` is a different object.

I'm not sure why this is yet.

### Expected behaviour

Before I rebased my pull requests on `master`, I was writing code more like this:

```js
Class('Foo').extends(withUpdate(class{}), ({ Super }) => {
  constructor() {
    Super(this).constructor()
    // use this like normal
  },
}))
```

In fact, this is how I was testing to make sure my pull requests worked, and they were working! Then I rebased, and I had to make those changes to get things working again.

Any ideas? Did any build dependencies change?

**Comment by trusktr** [comment] 2018-08-25 17:33
Oh! I know what it is!

I now recall the recent use of @WebReflection's `babel-plugin-transform-builtin-classes`.

This added some new code which is now returning a new `this` instead of using mine.

Hmmmm....

**Comment by trusktr** [comment] 2018-08-25 17:35
(added a `confirmed` label to make it easier to track which bugs are actually confirmed or reproduced)

**Comment by trusktr** [comment] 2018-08-25 17:38
Babel 7 is supposed to ship with equivalent of `babel-plugin-transform-builtin-classes`, so it may be worth see if using Babel 7 without `babel-plugin-transform-builtin-classes` fixes things.

**Comment by trusktr** [comment] 2018-08-25 17:39
For now I'll catch the constructor return value until we iron this one out.

**Comment by treshugart** [comment] 2018-08-31 04:27
> Babel 7 is supposed to ship with equivalent of babel-plugin-transform-builtin-classes, so it may be worth see if using Babel 7 without babel-plugin-transform-builtin-classes fixes things.

+1 to that.

> (added a confirmed label to make it easier to track which bugs are actually confirmed or reproduced)

Do we need that label? If we can't reproduce a bug it should probably be closed.

> For now I'll catch the constructor return value until we iron this one out.

Sounds like we can close this? Will do for now. Re-open if it's not.

**Closed by treshugart** 2018-08-31 04:27 UTC
Labels: bug, confirmed
