### ISSUE TITLE
Question: Testing

### ISSUE THREAD

**Issue by donifer** [skatejs/skatejs#1282] opened 2017-12-20 18:27 UTC
I'm kind of struggling trying to setup unit tests for a couple of components I'm building. Would be really helpful if there was a simple 1-2 component repo example with tests setup. 

I read the docs on `bore` which points me to `ssr` to be able to use Jest, but I ended up a bit more confused 😅. Currently not doing any ssr in my project.

**Comment by treshugart** [comment] 2017-12-20 22:42
Fair enough. I think a CLI or something could help this. The `skatejs/ssr` repo is basically a grab bag for doing anything in Node. Bore and SSR are separate tools that work well together here.

The Router component we've built has [tests](https://github.com/skatejs/skatejs/tree/master/packages/sk-router/src/__tests__) set up via the [Jest settings in the `package.json`](https://github.com/skatejs/skatejs/blob/master/package.json#L148). Ignore the mono-repo there and focus on the `testEnvironment` setting and the how the tests were written.

Happy to answer further questions here.

**Comment by donifer** [comment] 2017-12-21 19:02
Thanks for the pointers! I couldn't get it to work. Got some tests working using Karma + Mocha + bore running in chrome. Based on https://github.com/skatejs/generator-skatejs 

Not ideal but will get me going

**Comment by treshugart** [comment] 2017-12-22 02:31
What were the problems you encountered?

**Comment by treshugart** [comment] 2019-05-27 02:01
This can be considered a duplicate of #948, so closing.

**Closed by treshugart** 2019-05-27 02:01 UTC
Labels: question
