### ISSUE TITLE
5.0.0-alpha.5 fails to run in WebpackBin

### ISSUE THREAD

**Issue by mattdsteele** [skatejs/skatejs#1178] opened 2017-05-22 21:52 UTC
Using the WebpackBin template created in https://github.com/skatejs/skatejs/issues/1170, I updated the `skatejs` dependency to `5.0.0-alpha.5` and it fails to run. The error in the console is: `TypeError: modules[moduleId] is undefined`. Going back to alpha.3 works.

Strangely, if I download the project and run it with `npm start` locally, it appears to work fine.

I'm not sure if this is a bug in WebpackBin or if there's something new about alpha.5, but thought I'd let you know.

**Comment by treshugart** [comment] 2017-05-24 04:51
Hmmmm. I've seen this before and we should definitely see what the problem is.

**Comment by treshugart** [comment] 2017-05-26 05:01
@mattdsteele I've updated that bin (https://www.webpackbin.com/bins/-Kl276Ea5lcYZ3F-u3zv) and everything works now. Closing. If you're still seeing issues, please reopen. Thanks!

**Closed by treshugart** 2017-05-26 05:01 UTC
