### ISSUE TITLE
skatejs/bore: this.document || this.ownerDocument).querySelectorAll is not a function

### ISSUE THREAD

**Issue by superchris** [skatejs/skatejs#1419] opened 2018-03-06 20:06 UTC
## Bug report

* bore: 4.0.3

### Current behaviour

A test like this
```
test('flight-nav', () => {
  const wrapper = mount("<flight-nav></flight-nav>");
  expect(wrapper.all('leaflet-map').length).toEqual(1);
});
```
gives an error

```
    TypeError: (this.document || this.ownerDocument).querySelectorAll is not a function

      7 | });
      8 | 
      
      at Text.node.matches (node_modules/@skatejs/bore/umd/@skatejs/bore.js:137:57)
      at matches (node_modules/@skatejs/bore/umd/@skatejs/bore.js:141:6)
      at node_modules/@skatejs/bore/umd/@skatejs/bore.js:216:13
      at walk (node_modules/@skatejs/bore/umd/@skatejs/bore.js:285:3)
      at walkTree (node_modules/@skatejs/bore/umd/@skatejs/bore.js:306:9)
      at Wrapper.all (node_modules/@skatejs/bore/umd/@skatejs/bore.js:215:7)
      at Object.<anonymous> (flight-nav.test.js:9:18)
```

**Comment by treshugart** [comment] 2018-03-07 07:37
Yeah, this is because your environment wouldn't be supporting `querySelector`. If you're using `@skatejs/ssr`, we still haven't implemented that yet.

**Comment by trusktr** [comment] 2018-04-29 06:28
My components are gonna be hitting WebGL paths, etc, maybe `@skatejs/ssr` isn't the best for me in this case.

**Comment by treshugart** [comment] 2018-04-30 06:30
@trusktr probably not but it would be nice to see if something like https://github.com/stackgl/headless-gl works. For WebGL you may want a full browser environment depending on what you're doing. Regardless, `bore` works in a browser.

**Comment by trusktr** [comment] 2018-09-03 21:27
For reference, this is my Karma config with headless electron: https://github.com/trusktr/builder-js-package/blob/master/config/karma.config.js

**Comment by treshugart** [comment] 2019-05-27 02:33
Closing as there's no planned support for qSA and the rest of the issue is off topic.

**Closed by treshugart** 2019-05-27 02:33 UTC
Labels: package: bore, package: ssr
