### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by borisding1994** [skatejs/skatejs#890] opened 2016-10-27 06:53 UTC
v3.1.2 is work, v4.0.1 is wrong.

```
import { Component } from 'skatejs';
class ludComponent extends Component{
  attachShadow() {
    return this; // disabled ShadowDom
  }

  // However, in old Chrome / Opera or old polyfills
  // you might need to do this.
  createShadowRoot() {
    return this;
  }
}

export default ludComponent
```

**Comment by treshugart** [comment] 2016-10-27 10:44
Do you have a complete example that reproduces it? This code does nothing in isolation.

**Comment by treshugart** [comment] 2016-10-27 10:52
`ownerDocument` also doesn't appear in the Skate source code. I'm thinking this is from a dependency, but it'd be good to see a full example that reproduces this so that we can get to the bottom of it.

**Comment by treshugart** [comment] 2016-10-31 10:22
Going to leave this open for a few more days and will close after that if there's no activity.

**Comment by treshugart** [comment] 2016-11-03 09:04
Hey @borisding1994, closing as we can't reproduce and there hasn't been any activity here. Please reopen if you have anymore information. Thanks!

**Closed by treshugart** 2016-11-03 09:04 UTC
