### ISSUE TITLE
ternary expression in jsx doesn't work properly

### ISSUE THREAD

**Issue by stevemao** [skatejs/skatejs#749] opened 2016-08-26 07:15 UTC
```js
{condition?
  <Component>
    <input />
  </Component>
  :
  null
}
```

doesn't render `<Component>` properly but only `<input />` if `condition` is truthy.

**Comment by treshugart** [comment] 2016-08-26 07:48
Does this work with the standard vdom functions or if you write out using
the exposed Incremental DOM functions? If so, the issue probably lies with
the Babel plugin.

**Comment by stevemao** [comment] 2016-08-26 11:42
Sorry @treshugart , I didn't put enough details but I'd forget this :) I think this is a regression introduced recently cos it was working before. I'll give more information soon.

**Comment by treshugart** [comment] 2016-08-26 12:16
Ok, I just know we've had issues in the past. Switching to functions fixed things while using the JSX transformer broke things.

**Comment by Thinkscape** [comment] 2016-09-13 04:03
Interesting observation - it works better if you use empty strings, i.e.:
```jsx
{condition?
  <Component>
    <input />
  </Component>
  :
  ''
}
```
Somehow it makes it better (maybe a TextNode is created in its place?)

**Comment by stevemao** [comment] 2016-09-14 05:36
I can't reproduce my original issue anymore. The dependency is pinned so I didn't install a different dependency. but I have upgraded my chrome to 53. I don't know if that's the reason.

**Comment by bradleyayers** [comment] 2016-09-14 06:00
One scenario I had was ultimately due to https://github.com/tmorin/idomizer/issues/2. I'm going to close this issue, but will re-open if someone can provide a reproduction case.

**Closed by bradleyayers** 2016-09-14 06:00 UTC
