### ISSUE TITLE
RFC: a way of specifying properties that cause a property to be re-evaluated

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#269] opened 2015-08-03 18:42 UTC
For example:

```js
properties: {
  foo: {
    observe: [
      "bar",
    ],

    set(val) {
      console.log("foo set() called");
    }
  },

  bar: {},
}

// ...

let myEl = MyEl();
myEl.bar = 99;  // "foo set() called"
```

I was previously using `this.propertyName = this.propertyName` to trigger this manually, but it has stopped working in one of skate's latest releases (`master`/`lifecycle-exploration`), probably as a measure to improve performance, however now it is impossible to manually trigger the property's setter unless you move the setter's code into the `prototype` and to call that method whenever you want to re-evaluate the property.

**Comment by treshugart** [comment] 2015-08-03 22:23
Yeah, those are still in the experimental stage. FWIW I do find them extremely useful but when I brought it to the table the feeling I got was that they should be a separate extension to Skate as it didn't feel like they should belong to the base library. I was of two minds. On one side it was very useful, but on the other it wasn't a complete implementation.

I'm happy to try and get it going again but I think they need to be thought of in terms of a simple, but fairly complete solution.

- Observable properties on host.
- Host able to observe properties on descendants.
- Host able to observe properties on future descendants.
- Dependencies placed on all types of observable properties from within a single property definition.
- Should we observe

**Comment by marcoms** [comment] 2015-08-04 10:17
The "observe" name was probably poor nomenclature on my part for what I wanted to achieve at a basic level, which is to just have a way to manually trigger a property's setter. Having this done declaratively using `observe` would be ideal, however any other solution that would enable me to trigger a properties setter would resolve this for me, perhaps even in the skate API.

**Comment by treshugart** [comment] 2015-08-07 12:29
I think a certain level of this would be useful. In your example above, what would `observe` mean? Would it be the property that declared it listening to the properties in the `observe` array and triggering its `set` when they fire? Or would it be the other way around?

Another question is would this API cover only properties on the component in which they're declared, or would it listen for properties on descendant components?

I'm interested in fleshing out this idea more as it would be a useful feature, even if it was a plugin.

**Comment by marcoms** [comment] 2015-08-07 13:03
>the property that declared it listening to the properties in the observe array and triggering its set when they fire

That's right

>would this API cover only properties on the component in which they're declared, or would it listen for properties on descendant components?

I would expect that by default it would only cover the single component, whereas something could optionally be passed to the observe property to specify the latter (like `HTMLElement#clone(deep=false)`)

Perhaps like:

```js
// array form: all properties observed only on the component and ignoring descendant components
observe: [
  "propA",
  "propB",
]

// object form: "deep" and "shallow" properties provided
observe: {
  deep: [
    "propA",
    "probB",
  ],

  shallow: [
    "propC",
  ],
}
```

**Comment by treshugart** [comment] 2015-08-10 01:15
When I was messing around with ways to do this, I came up with a way where you could use dot-notation to reach into descendants. There's a few assumptions you can make here:

1. You will never be observing properties on non-skate-components.
2. All components will have a registered component name.
3. The last part of the dot-notated identifier is always the name of the property being observed.
4. If no dot-notated parts exist, then we're observing the current element.

Because of 1 and 2, you can use element IDs as the dot-notated parts and transform that into a selector to use with event delegation. The only downside is that you're bubbling property events that could have an impact on performance (not tested yet).

For example:

```js
observe: [
  'my-child.propA',
  'my-descendant.propB',
  'my-child.my-descendant.propC'
]
```

Event delegation is more robust than other methods because you'd have to use a combination of `querySelectorAll()` and `MutationObserver`s in order to bind handlers directly to descendant elements.

**Comment by treshugart** [comment] 2015-08-10 01:17
FWIW I actually like the name `observe`. I was only clarifying intent before; the name wasn't confusing.

**Comment by marcoms** [comment] 2015-08-11 13:51
I like this solution. With the last array item in your `observe` example though:

> `'my-child.my-descendant.propC'`

Is `my-descendant` a class name or an id? If it's an id then shouldn't it be rewritten as `my-descendant.propC` (as there is no need to over-qualify an id)?

**Comment by treshugart** [comment] 2016-01-12 03:14
@marcoms 

I think I'm going to close this as invalid. I've got a couple reasons for it.

I prefer to be explicit about updating properties. The implicitness of having one setter trigger another, and then that setter possibly triggering another makes the code harder to reason about and prone to recursion bugs, or unexpected behaviour that is hard to track down.

Adding this suggests that using observables are the recommended way to do properties and I'm no longer a huge fan of that. I'd prefer to keep Skate less opinionated in this regard especially since this can be implemented in a separate module if there is a desire.

You okay with that? Happy to discuss further.

**Comment by marcoms** [comment] 2016-01-12 18:30
I'm OK with that. In fact my use-case has actually drifted away from this sort of idea - I've found using a shared function on the prototype is very adequate for my needs.

**Comment by treshugart** [comment] 2016-01-12 21:38
Sweet! Thanks for the feedback. Would you mind sharing your method of doing in case others have a similar use-case? Cheers!

**Closed by treshugart** 2016-01-12 21:38 UTC
Labels: rfc

**Comment by marcoms** [comment] 2016-01-13 09:49
Not very pretty I'm afraid, but good enough for me... :smiley:

```js
prototype: {
  _doCommonTasks() {
    // *common tasks*
  },
},

properties: {
  a: {
    set(el) {
      // a stuff

      el._doCommonTasks();
    },
  },

  b: {
    set(el) {
      // b stuff

      el._doCommonTasks();
    },
  },
},
```

**Comment by treshugart** [comment] 2016-01-13 11:51
@marcoms you could put it in a function and pass in the element making it a little "cleaner" (subjective). But I don't necessarily think this is an ugly approach. It's explicit; easier to reason about than following a trail of observers.
