### ISSUE TITLE
withChildren crashes with "Cannot set property props... " message

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1466] opened 2018-07-15 17:08 UTC
## Bug report

* Skate version: 5.2.1 (`npm info skatejs version`)
* Affected browsers (and versions): Chrome 67, Opera

### Current behaviour

Example created for https://github.com/skatejs/skatejs/issues/1186 (https://codesandbox.io/s/oqy3oozx9z) crashes with message "Cannot set property props of #<_class2> which has only a getter"

Really weird. Could not figure why

### Expected behavior

Should not crash

**Comment by blikblum** [comment] 2018-07-18 03:42
The crash reason is that preact renderer (and React/Snabbdom renderers) override `props` property getter but do not override `props` property setter. 

BTW: the children key set by withChildren is override by the children key returned by the renderers, which makes its useless

Anyway, more reasons to [not set children in props](https://github.com/skatejs/skatejs/issues/1443)

**Comment by blikblum** [comment] 2018-07-20 12:44
I confirm that this bug occurs also with snabbdom renderer and esnext builds (not only in codesandbox)

**Comment by trusktr** [comment] 2018-07-23 01:47
1. If you add your own setter, that seems to make it work: https://codesandbox.io/s/4qlzy1853x
2. Is there another way to fix it other than removing it? I'm not familiar with snabbdom though.
3. If we did remove that rom snabbdom, would we want to remove it from all the renderers?
4. Another question, do we want to let `this.props.children` be just the native children? Or is providing a `slot` element or vnode actually useful?
  - Note the user can also make their own slot element.
  - Note also that `this.children` also always returns the native children
5. `withChildren` does not seem to set the `children` in `static props`, so is that even reactive? Will it call `triggerUpdate` if that changes? (I haven't tested tried using `withChildren` yet.)

**Comment by trusktr** [comment] 2018-07-23 05:11
About point 6, this test shows that methods `childrenUpdated`, `updated`, or `render` do not get called when children are updated:

https://codesandbox.io/s/qq5z251px9

After the timeout, why does `childrenUpdated` not get called again?

**Comment by trusktr** [comment] 2018-07-23 05:14
Oops, I forgot to call `super.childrenUpdated()`, but the behavior is the same: https://codesandbox.io/s/2x1jlv7o50

**Comment by trusktr** [comment] 2018-07-23 05:44
Doh! I was forgetting to call `super.connectedCallback`. It's easy to overlook that. Sorry for the spam.

So this works: https://codesandbox.io/s/xl5q8vj78w

And if we call `updated()` inside of `childrenUpdated` then we get the desired updates: https://codesandbox.io/s/nrzpmx8lnl

IMO, let's

- get rid of `this.props.children` being a `<slot>`, as we can do that already in the markup
- make sure that renderers aren't trying to set `props`
- make child updates hook into `updated` or `render` lifecycle methods (similar to other frameworks like React or Preact).
- double check definitions of `props` have both a `set` and `get`.

Thoughts on that @blikblum ?

**Comment by blikblum** [comment] 2018-07-23 12:47
> What if we add the setter instead of removing the getter?
To avoid breaking change yes. For v6, just remove returning children in renderer

>If we did remove that from snabbdom, would we want to remove it from all the other renderers?
Some renderers like lit-html do not override props. For the others in V6. Since snabbdom is undocumented and buggy, should not be considered breaking

> Do we want to let this.props.children be just the native children? Or is providing a slot element or vnode actually useful?
Note the user can also make their own slot element.
Note also that this.children also always returns the native children
> If this.children is the native children, but this.props.children is a vnode or slot, is the inconsistency okay? I'm not sure, but I think I'd prefer for them to be consistent (actual children). We're dealing with Custom Elements after all.

These are the reasons described in #1443

> withChildren does not seem to define children in static props, so is it even reactive? Will it call triggerUpdate if it changes? (I haven't tried using withChildren yet.)

static props should not be modified at all. And IMO opinion withChidren should not be reactive

**Comment by blikblum** [comment] 2018-07-23 14:52
Regarding withChildren as a whole i would not provide a default childrenUpdated callback at all. It would let user do whatever he wants (be manipulate the children or store a reference elsewhere).

Aside of fixing this bug and being less opinionated, it will improve performance since it will create a mutation observer only in the cases the user is interested in the children mutations

BTW: this.children is empty when used with shadow dom which is probably not what a user would expect.

**Comment by treshugart** [comment] 2018-07-27 06:09
The issue is here: https://github.com/skatejs/skatejs/blob/master/packages/renderer-preact/src/index.js#L26 and you've only defined a getter for `props`. This is a legitimate bug. What we could do instead is to define a getter that calls `super.props` and mixes in a `children` prop if not already defined.

**Comment by treshugart** [comment] 2018-07-27 06:12
> Aside of fixing this bug and being less opinionated, it will improve performance since it will create a mutation observer only in the cases the user is interested in the children mutations

What we could do is instead check to see if the consumer defined a `props.children` *or* provided a `childrenUpdated`. This way it doesn't try to define it, it only sets it if it exists in `props` and only calls `childrenUpdated` if they're updated.

**Comment by treshugart** [comment] 2018-12-06 08:31
Will be fixed in the next major releases.

**Closed by treshugart** 2018-12-06 08:31 UTC
Labels: bug
