### ISSUE TITLE
Rendering to light DOM is not works properly. When parent custom-element is rerendering, child custom-element content is lost.

### ISSUE THREAD

**Issue by majo44** [skatejs/skatejs#1197] opened 2017-07-06 22:53 UTC
Example: https://www.webpackbin.com/bins/-KoOzIcTUxPE7oDkLAWq
I described this problem in https://github.com/developit/preact/issues/654
Please vote for updates in preact :) and apply this changes to skatejs

**Comment by majo44** [comment] 2017-08-28 15:33
The problem do not appear if I switch the render to https://github.com/snabbdom/snabbdom + https://github.com/Swizz/snabbdom-pragma. So I wait for #1217 :)

**Comment by treshugart** [comment] 2017-08-29 02:41
Interesting! There's a branch with some of the work already done. It's at the point where we've prepped it to move. @chrisdarroch knows the details but if you see something you might be able to help on, happy to discuss. I opened #1218 to discuss etc there.

**Comment by treshugart** [comment] 2017-09-21 00:34
Hey @majo44, we just merged moving out the preact renderer. Can you see if there's anything else we need to do here? I can't tell if there is or not. Thanks!

**Comment by chrisdarroch** [comment] 2017-09-21 07:25
This appears to be fixed when using Skate 5. Here's the updated example, @majo44  https://www.webpackbin.com/bins/-KuYJlTdy2SWIN_FVu7J

**Comment by majo44** [comment] 2017-09-21 07:49
@chrisdarroch 
Thank you. 
But unfortunately  as I see this example not working properly, the attribute change is not triggering the second render. I will look at this a bit later.

**Comment by chrisdarroch** [comment] 2017-09-21 09:56
hmm, I'll have to leave that part with you and @treshugart. Given that the child is rendering static text and isn't invoking the `h()` function, I'm not sure whether I'd expect the child to re-render after changing the attribute on the parent. I'm pretty new to react/preact, so I'm missing a load of context to understand what should be expected behaviour here.

**Comment by treshugart** [comment] 2017-09-21 10:37
Updated bin: https://www.webpackbin.com/bins/-KuYl9Fid-xH_0M81njR.

Ok, so this really isn't an issue with Skate. Sure, the content is lost but this is due to Preact's diffing algorithm. Why not just use Shadow DOM and polyfill it? 

Alternatively, you *could* use something like this: https://gist.github.com/treshugart/e19c2be255448cd31d261f2e8db2127c, but YMMV with it. I'm ambivalent about making it "a thing", as in giving it a repo because of how close we really are to having shadow DOM everywhere.

Here's an updated bin with the pseudo shadow DOM base class: https://www.webpackbin.com/bins/-KuYx4lYlP6D_5JWqbGJ. No CSS encapsulation is happening there, but it is possible. The key with that implementation is that you must implement `childNodes`. It's a dumb implementation, so you must decide what to do with them.

**Comment by treshugart** [comment] 2017-09-21 10:38
I'm going to close this now since this is really a renderer issue, not Skate, but I'm more than happy to discuss this further here, or separately.

**Closed by treshugart** 2017-09-21 10:38 UTC
Labels: bug
