### ISSUE TITLE
web components with github url

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#753] opened 2016-08-29 22:10 UTC
I just tried to install skatejs-web-components

warn Error on processPackageConfig
     Package.json dependency webcomponents.js set to github:webcomponents/webcomponentsjs#b77ca74, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

**Comment by treshugart** [comment] 2016-08-30 06:41
I'm not sure I understand the problem. Why can't you just `npm i skatejs-web-components --save`? JSPM has an NPM adapter and if you want it via CDN you can use NPMCDN (now unpkg), right? I'm not sure what you mean by "GitHub or another registry".

**Comment by thepian** [comment] 2016-08-30 12:57
Your dependencies are a bit problematic. What is the upgrade path in the future if I use SkateJS it seems that it is made to work only with a specific web components version

from the project package.json

  "dependencies": {
    "es6-collections": "0.x",
    "skatejs-named-slots": "1.x",
    "webcomponents.js": "webcomponents/webcomponentsjs#b77ca74"
  },

**Comment by treshugart** [comment] 2016-08-30 23:39
The problem is that the webcomponents polyfill hasn't been released as a version yet. When it is, we'll fuzzy version it. There's currently an open issue for using https://github.com/WebReflection/document-register-element, but there are still failing tests in IE. Once those are resolved, we'll consider using that as it's semantically versioned and is mostly complete.

If you need to, you can consume the polyfills separately. The skatejs-web-components module was created so it's simpler for most use-cases.

How exactly are you installing it that's causing problems? I couldn't quite get that from your original issue. We are currently using NPM without any issues.

**Comment by treshugart** [comment] 2016-08-31 00:41
Just opened https://github.com/skatejs/web-components/pull/8 to go against that versioned polyfill.

**Comment by treshugart** [comment] 2016-09-02 06:20
Hey @thepian, I've just merged the PR implementing support for https://github.com/WebReflection/document-register-element. If you use the latest from https://github.com/skatejs/web-components you should be getting that polyfill instead and shouldn't have any dependency issues as it's strictly versioned. Closing this now, but feel free to reopen if you still have any issues.

**Closed by treshugart** 2016-09-02 06:20 UTC
Labels: question
