### ISSUE TITLE
Not resolving elements in Google Chrome

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#231] opened 2015-06-25 23:42 UTC
Starting from this release: https://github.com/skatejs/skatejs/commit/11d713f57ac91792c270ac91a31e7016027809d2 of `dist/skatejs` my custom elements don't get resolved in Google Chrome. It's working in Firefox.

This is my test template: https://github.com/obshtestvo/signali-theme/blob/master/research/index.html

I even tried registering components with just the name and empty definition (`{}`).

**Comment by antitoxic** [comment] 2015-06-25 23:54
*Related finding:* If I put `console.log(this.tagName)` in either `template` or `attached` lifecycle callbacks the problem disappears.

Seems like this trigger something that is not triggered?

**Comment by treshugart** [comment] 2015-06-26 00:25
Interesting. Are you able to isolate this issue in a sample test script? I'm unable to reproduce the same issue on master latest.

Also, as a side note, master isn't considered stable enough to develop from. I'd recommend using the latest tag unless you're just playing around. Master is subject to a lot of changes right now due to us spiking / removing and moving around features as we move toward 1.0.

**Comment by antitoxic** [comment] 2015-06-28 15:22
@treshugart I have the minimal example here: http://run.plnkr.co/ysVY8T3KPk4yxYkU/

Take note that I can't replicate it fully so try loading it several times. It doesn't not happen every time with this example but it does happen.

`<footer-wrapper>` gets resolved but `<page>` and other elements don't.

**Comment by antitoxic** [comment] 2015-06-28 15:25
Chrom version: 43.0.2357.130 . It says it's the latest one.

**Comment by treshugart** [comment] 2015-06-28 23:41
Hmm, that link just 404's for me. If you can paste your sample html here (and JS) I can reconstruct it and have a play with it.

**Comment by antitoxic** [comment] 2015-07-04 15:23
Try this before manually copying the html: http://embed.plnkr.co/bW8Xw5CM6TWNkOpsEgiJ/preview

It should load.

***Otherwise:***

The html is quite bulky (i havent cleaned all of it):

```html
<!DOCTYPE html>
<html>

  <head>
  </head>

  <body>
    <loader target="page"></loader>
<page>
    <cover>
        <top-nav>
            <menu>
                Категории
                <menu-column>
                    <h2>Граждански</h2>
                    <ul>
                        <li><a href="#">Бракониерство</a></li>
                        <li><a href="#">Престъпления - кражба, насилие...</a></li>
                        <li><a href="#">Изгубени вещи</a></li>
                        <li><a href="#">Пътно-транспортни</a></li>
                        <li><a href="#">Градска среда</a></li>
                        <li><a href="#">Корупция, измама</a></li>
                    </ul>
                </menu-column>
                <menu-column>
                    <h2>Престъпност</h2>
                    <ul>
                        <li><a href="#">Нарушаване на човешки права</a></li>
                        <li><a href="#">Изборни нарушения</a></li>
                        <li><a href="#">Хранителна индустрия</a></li>
                        <li><a href="#">Тютюнопушене</a></li>
                        <li><a href="#">Изгубени вещи</a></li>
                        <li><a href="#">Пътно-транспортни</a></li>
                    </ul>
                </menu-column>
                <menu-column>
                    <h2>Градски</h2>
                    <ul>
                        <li><a href="#">Бракониерство</a></li>
                        <li><a href="#">Престъпления - кражба, насилие...</a></li>
                        <li><a href="#">Изгубени вещи</a></li>
                        <li><a href="#">Пътно-транспортни</a></li>
                        <li><a href="#">Градска среда</a></li>
                        <li><a href="#">Корупция, измама</a></li>
                    </ul>
                </menu-column>
                <menu-column>
                    <h2>Потребителски</h2>
                    <ul>
                        <li><a href="#">Нарушаване на човешки права</a></li>
                        <li><a href="#">Изборни нарушения</a></li>
                        <li><a href="#">Хранителна индустрия</a></li>
                        <li><a href="#">Тютюнопушене</a></li>
                    </ul>
                </menu-column>
            </menu>
            <login-box anonymous action="login">
                Вход
            </login-box>
            <login-box action="profile">
                <img src="https://scontent-fra3-1.xx.fbcdn.net/hphotos-xap1/v/t1.0-9/10475589_10205205672674157_3404584188073166110_n.jpg?oh=43b727782cd4b32f9e6f6bff1ea02742&oe=55F8F8A1">
                <strong>Boyan Stoychev</strong>
                <ul>
                    <li><a href="#">Настройки</a></li>
                    <li><a href="#">Изход</a></li>
                </ul>
            </login-box>
            <logo align="center-xy" action="home" color="light" size="large"></logo>
        </top-nav>
        <intro interval="medium">
            <call-to-action align="center">
                <h1>Пoдай сигнал</h1>
                <p>Намери и подай сигнал към над <underline>121</underline> институции в над <underline>23</underline> области.</p>
            </call-to-action>
            <form action="">
                <select-dropdown id="drop2" name="dropdown2" location mainsearch>
                    <label>къде?</label>
                </select-dropdown>
                <select-dropdown id="drop" name="dropdown" multiple mainsearch>
                    <label>проблем</label>
                    <value id="2" selected>corruption</value>
                    <value id="3" >ecology</value>
                    <value id="5" >Красота майна</value>
                    <value id="4" >Чичковите чвеасд асд асд ас дасд сas das dasdsdasdasdссд асд </value>
                    <value id="6" >асдасда сд РАСФДАСФасдасд </value>
                </select-dropdown>
                <action-button link align="right" action="google.com" color="red">
                    търси
                </action-button>
            </form>
        </intro>
    </cover>
    <featured>
        <cards-area>
            <headline size="large" align="center">Популярни сайтове</headline>
            <tabs align="center">
                <li><a href="#">София</a></li>
                <li><a href="#">Пловдив</a></li>
                <li><a class="active" href="#">Варна</a></li>
                <li><a href="#">Бургас</a></li>
                <li><a href="#">Стара загора</a></li>
            </tabs>
            <cards>
                <card>
                    <a href="#" class="logo"><img src="test/logo1.jpg" alt=""/></a>
                    <a href="#" class="name">Държавно Горско Стопанство гр. Враца</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                        <tag action="google.com">полиция</tag>
                        <tag action="google.com">граница</tag>
                        <tag action="google.com">връзка</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
                <card>
                    <a href="#" class="logo"><img src="test/logo2.png" alt=""/></a>
                    <a href="#" class="name">Гранична полиция</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
                <card>
                    <a href="#" class="logo"><img src="test/logo3.jpg" alt=""/></a>
                    <a href="#" class="name">Омбудсман Република България</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                        <tag action="google.com">полиция</tag>
                        <tag action="google.com">граница</tag>
                        <tag action="google.com">връзка</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
                <card>
                    <a href="#" class="logo"><img src="test/logo4.jpg" alt=""/></a>
                    <a href="#" class="name">Гореща линия за безопасен Интернет</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                        <tag action="google.com">полиция</tag>
                        <tag action="google.com">граница</tag>
                        <tag action="google.com">връзка</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
            </cards>
            <more-button align="right" action="seemore.html">виж всички</more-button>
        </cards-area>
        <cards-area>
            <headline size="large" align="center">Изборни нарушения</headline>
            <cards>
                <card>
                    <a href="#" class="logo"><img src="test/logo1.jpg" alt=""/></a>
                    <a href="#" class="name">Държавно Горско Стопанство гр. Враца</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                        <tag action="google.com">полиция</tag>
                        <tag action="google.com">граница</tag>
                        <tag action="google.com">връзка</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
                <card>
                    <a href="#" class="logo"><img src="test/logo2.png" alt=""/></a>
                    <a href="#" class="name">Гранична полиция</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
                <card>
                    <a href="#" class="logo"><img src="test/logo3.jpg" alt=""/></a>
                    <a href="#" class="name">Омбудсман Република България</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                        <tag action="google.com">полиция</tag>
                        <tag action="google.com">граница</tag>
                        <tag action="google.com">връзка</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
                <card>
                    <a href="#" class="logo"><img src="test/logo4.jpg" alt=""/></a>
                    <a href="#" class="name">Гореща линия за безопасен Интернет</a>
                    <a href="#" class="category">Тютюнопушене на обществени места</a>
                    <a href="#" class="location">София - град</a>
                    <tags>
                        <tag action="google.com">конфликт на интереси</tag>
                        <tag action="google.com">полиция</tag>
                        <tag action="google.com">граница</tag>
                        <tag action="google.com">връзка</tag>
                    </tags>
                    <rating>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="full"></star>
                        <star type="half"></star>
                        <star type="empty"></star>
                        <a class="comments" href="#">14 коментара</a>
                    </rating>

                    <a class="action" href="#">Подай сигнал</a>
                </card>
            </cards>
            <more-button align="right" action="seemore.html">виж всички</more-button>
        </cards-area>
        <donation>
            <p>Този сайт се задвижва благодарение на неговите потребители. Благодарим!</p>
            <action-button link align="center" action="google.com" color="white">
            Добави
            </action-button>
        </donation>
    </featured>
    <footer-wrapper>
        <logo action="home" color="dark" size="medium" align="right"></logo>
        <footer-navigation>
            <footer-column>
                <h5>За проекта</h5>
                <li><a href="#">За нас</a></li>
                <li><a href="#">За контакти</a></li>
                <li><a href="#">За Общество.БГ</a></li>
            </footer-column>
            <footer-column emphasis>
                <h5>Избрани категории</h5>
                <li><a href="#">Бракониерство</a></li>
                <li><a href="#">Престъпления - кражба, насилие </a></li>
                <li><a href="#">Изгубени вещи</a></li>
                <li><a href="#">Пътно-транспортни</a></li>
                <li><a href="#">Градска среда</a></li>
                <li><a href="#">Корупция, измама</a></li>
            </footer-column>
            <footer-column>
                <li><a href="#">Бракониерство</a></li>
                <li><a href="#">Престъпления - кражба, насилие  кражба, насилие </a></li>
                <li><a href="#">Изгубени вещи</a></li>
                <li><a href="#">Пътно-транспортни</a></li>
                <li><a href="#">Градска среда</a></li>
                <li><a href="#">Корупция, измама</a></li>
            </footer-column>
        </footer-navigation>
        <sponsors>
            <h5>Спонсори</h5>
            <li><a href="#"><img src="test/sponsor-geagrants.png" alt=""/></a></li>
            <li><a href="#"><img src="test/sponsor-bluelink.png" alt=""/></a></li>
            <li><a href="#"><img src="test/sponsor-obhstestvo.png" alt=""/></a></li>
        </sponsors>
    </footer-wrapper>
    <!--<picker>admin</picker>-->
    <!--<playground>-->
        <!--<action-button align="center" action="google.com" color="white">-->
            <!--Логни Са Ва!-->
        <!--</action-button>-->
        <!--<action-button align="center" action="google.com" color="purple" secondary outlined>-->
            <!--Ари Ва!-->
        <!--</action-button>-->
        <!--<checkbox id="asdasd" name="test" checked>Test checkbox</checkbox>-->
        <!--<radio-button id="rarar" name="test" >Test radio</radio-button>-->
        <!--<radio-button id="rarar2" name="test" >Test radio</radio-button>-->
        <!--<radio-button id="rarar3" name="test" >Test radio</radio-button>-->
        <!--<breadcrumb>-->
            <!--<crumb action="google.com">Home</crumb>-->
            <!--<crumb action="google.com">This is not so home</crumb>-->
            <!--<crumb action="google.com">Far away from home</crumb>-->
        <!--</breadcrumb>-->

        <!--<tabs-nav align="left">-->
            <!--asasas-->
        <!--</tabs-nav>-->
    <!--</playground>-->
    <fader style="display:none; ">
        <!--Modal Window Login-->
        <modal login style="display: ">
            <headline size="large" placement="modal" align="center">Вход</headline>
            <section>
                <form action="">
                    <input-field size="full" id="name" type="text">
                        потребителско име
                    </input-field>
                    <input-field size="full" id="password" type="password">
                        Парола
                    </input-field>
                    <div class="clearfix">
                        <action-button link align="left" action="google.com" color="red">
                            вход
                        </action-button>
                        <forbidden-password action="gotoregister.com">
                            Забравена парола?
                        </forbidden-password>
                    </div>

                </form>
            </section>
            <section>
                <headline size="small">Вход през Facebook</headline>
                <notification information size="small">
                    <p>Easy one click sign in. We won't post anything without your permission.</p>
                </notification>
                <social-button facebook action="google3.com"></social-button>
                <social-button google action="fb.com"></social-button>
            </section>
            <footer>
                <a href="#">Направи си регистрация</a>
            </footer>
        </modal>
        <!--Modal window Register-->
        <modal style="display: none;">
            <headline size="large" placement="modal" align="center">Регистрация</headline>
            <div class="clearfix">
                <section>
                    <form action="">
                        <input-field size="full" id="name" type="text">
                            Име
                        </input-field>
                        <input-field size="full" id="email" type="email">
                            имейл адрес
                        </input-field>
                        <notification information size="small">
                            <p>
                                Easy one click sign in. We won't post anything without your permission.
                            </p>
                        </notification>
                        <input-field size="full" id="password" type="password">
                            Парола
                        </input-field>
                        <input-field size="full" id="password2" type="password">
                            повторете паролата
                        </input-field>
                        <action-button link align="left" action="google.com" color="red">
                            вход
                        </action-button>
                    </form>
                </section>
                <section>
                    <headline size="small">Вход през Facebook</headline>
                    <notification information size="small">
                        <p>Easy one click sign in. We won't post anything without your permission.</p>
                    </notification>
                    <social-button facebook action="google3.com"></social-button>
                    <social-button google action="fb.com"></social-button>
                </section>
            </div>
        </modal>
        <!--Modal Settings-->
        <modal style="display: none;">
            <headline size="large" placement="modal" align="center">Настройки</headline>
            <tabs align="center">
                <li><a href="#">Име</a></li>
                <li><a class="active" href="#">Имейл</a></li>
                <li><a href="#">Парола</a></li>
            </tabs>
            <profile-settings>
                <form action="">
                    <input-field size="standart" id="email" type="email" placeholder="office@obshtestvo.bg">
                        имейл адрес
                    </input-field>
                    <action-button link align="left" action="google.com" color="red">
                        запази
                    </action-button>
                </form>
            </profile-settings>
        </modal>
        <!--Modal Add Signal-->
        <modal style="display: none;">
            <headline size="large" placement="modal" align="center">Добави сигнал</headline>
            <select-dropdown id="drop" name="dropdown" multiple size="standart" >
                <label>Местонахождение</label>
                <value id="2" selected>corruption</value>
                <value id="3" >ecology</value>
                <value id="5" >Красота майна</value>
                <value id="4" >Чичковите чвеасд асд асд ас дасд сas das dasdsdasdasdссд асд </value>
                <value id="6" >асдасда сд РАСФДАСФасдасд </value>
            </select-dropdown>
            <select-dropdown id="drop2" name="dropdown2" location size="standart">
                <label>Категория</label>
            </select-dropdown>
            <filters>
                <strong>изисквания</strong>
                <checkbox id="register" name="register" unchecked>Регистрация</checkbox>
                <checkbox id="photo" name="photo" checked>Снимка</checkbox>
                <checkbox id="isign" name="isign">Ел. Подпис</checkbox>
                <checkbox id="name" name="name">Име</checkbox>
                <checkbox id="email" name="email">Е-mail</checkbox>
                <checkbox id="egn" name="egn">EГН</checkbox>
                <checkbox id="address" name="address">Адрес на подателя</checkbox>
                <checkbox id="location" name="location">Локация на сигнала</checkbox>
            </filters>
            <filters>
                <strong>Други опции</strong>
                <checkbox id="belang" name="belang" checked>Мултиезичност</checkbox>
                <checkbox id="warr" name="warr">Гаранция за отговор</checkbox>
                <checkbox id="anonymous" name="anonymous">Анонимност</checkbox>
                <checkbox id="mobile" name="mobile">Мобилна версия</checkbox>
                <checkbox id="endrec" name="endrec">Краен приемник</checkbox>
                <checkbox id="verification" name="verification">Верификация на сигнала? </checkbox>
                <checkbox id="confirm" name="confirm">Потвърждаване на сигнала?</checkbox>
            </filters>

            <action-button link align="left" action="google.com" color="red">
                Добави
            </action-button>
        </modal>
        <!--Modal messege for allert, success, error-->
        <modal style="display: none;">
            <headline size="large" placement="modal" align="center">Регистрация</headline>
            <notification success size="popup">
                <strong>Успешна регистрация</strong>
                <p>Easy one click sign in. We won't post anything without your permission.</p>
            </notification>
        </modal>
    </fader>

</page>
        <google-analytics account="asd"></google-analytics>

  <script src="https://rawgit.com/skatejs/skatejs/11d713f57ac91792c270ac91a31e7016027809d2/dist/skatejs.js"></script>
  <script src="script.js"></script>
  </body>
</html>
```

Script:

```js
skate('loader', {template: function() {}});
skate('cover', {template: function() {}});
skate('intro', {template: function() {}});
skate('top-nav', {template: function() {}});
skate('login-box', {template: function() {}});
skate('logo', {template: function() {}});
skate('call-to-action', {template: function() {}});
skate('underline', {template: function() {}});
skate('google-analytics', {template: function() {}});
skate('action-button', {template: function() {}});
skate('breadcrumb', {template: function() {}});
skate('crumb', {template: function() {}});
skate('tabs', {template: function() {}});
skate('checkbox', {template: function() {}});
skate('radio-button', {template: function() {}});
skate('select-dropdown', {template: function() {}});
skate('value', {template: function() {}});
skate('menu', {template: function() {}});
skate('menu-column', {template: function() {}});
skate('headline', {template: function() {}});
skate('cards-area', {template: function() {}});
skate('cards', {template: function() {}});
skate('card', {template: function() {}});
skate('tags', {template: function() {}});
skate('tag', {template: function() {}});
skate('rating', {template: function() {}});
skate('star', {template: function() {}});
skate('more-button', {template: function() {}});
skate('donation', {template: function() {}});
skate('footer-wrapper', {template: function() {}});
skate('footer-navigation', {template: function() {}});
skate('footer-column', {template: function() {}});
skate('sponsors', {template: function() {}});
skate('fader', {template: function() {}});
skate('modal', {template: function() {}});
skate('input-field', {template: function() {}});
skate('notification', {template: function() {}});
skate('social-button', {template: function() {}});
skate('forbidden-password', {template: function() {}});
skate('profile-settings', {template: function() {}});
skate('filters', {template: function() {}});
skate('page', {template: function() {}});
skate('popup', {template: function() {}});
```

**Comment by treshugart** [comment] 2015-07-07 06:01
It's probably related to the fix that landed in #219 (issue #220). We'll end up restoring the `interactive` check while also hacking for IE10 and IE9. We'll close this when we land that fix.

**Comment by antitoxic** [comment] 2015-07-09 08:14
Cool. I'm standing by and curiously looking into the new structure.

**Comment by treshugart** [comment] 2015-07-09 08:33
It's still changing as we thrash it but if you have any questions or
comments we're happy to hear / answer. Thanks for all the issues you've
contributed thus far :)

**Comment by treshugart** [comment] 2015-07-31 00:02
Closing this now as it doesn't seem like there's any actions require for it.

**Closed by treshugart** 2015-07-31 00:02 UTC
Labels: bug

**Comment by antitoxic** [comment] 2015-07-31 07:33
Confirmed, it's working with `master` branch (the one that now requires separate repo for type attribute elements).

**Comment by treshugart** [comment] 2015-07-31 07:41
:+1:
